In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
text=['the car is driven on the road','the truck is driven on the highway']

In [3]:
vectorizer=CountVectorizer()
vectorizer.fit(text)

CountVectorizer()

In [4]:
print(vectorizer.vocabulary_)

{'the': 6, 'car': 0, 'is': 3, 'driven': 1, 'on': 4, 'road': 5, 'truck': 7, 'highway': 2}


In [5]:
newvector=vectorizer.transform(text)
print(newvector.toarray())

[[1 1 0 1 1 1 2 0]
 [0 1 1 1 1 0 2 1]]


# TF-IDF

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
text=['the car is driven on the road','the truck is driven on the highway']

In [8]:
print(text)

['the car is driven on the road', 'the truck is driven on the highway']


In [10]:
tfidf=TfidfVectorizer()
tfidf.fit(text)

TfidfVectorizer()

In [11]:
print(tfidf.idf_)

[1.40546511 1.         1.40546511 1.         1.         1.40546511
 1.         1.40546511]


In [12]:
print(tfidf.vocabulary_)

{'the': 6, 'car': 0, 'is': 3, 'driven': 1, 'on': 4, 'road': 5, 'truck': 7, 'highway': 2}


In [13]:
tfidf_vector=tfidf.transform(text)

In [14]:
tfidf_vector

<2x8 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [15]:
tfidf_vector.toarray()

array([[0.42471719, 0.30218978, 0.        , 0.30218978, 0.30218978,
        0.42471719, 0.60437955, 0.        ],
       [0.        , 0.30218978, 0.42471719, 0.30218978, 0.30218978,
        0.        , 0.60437955, 0.42471719]])